// ============================================================================
// GradNiche University & Program Data Layer
// WARNING: This file is automatically compiled from raw JSON profiles.
// Do not edit this file directly. Instead, modify the JSON profiles under
// /data/universities/ and run scripts/sync.ps1 to compile.
// ============================================================================

export interface Program {
  id: string;
  name: string;
  level: 'Masters' | 'MBA';
  duration: string;
  tuition: number;
  about: string;
  school: string;
  isSTEM: boolean;
  requirements: string[];
  applyLink: string;
  ieltsScore?: string;
  greScore?: string;
  gmatScore?: string;
  duolingoScore?: string;
  pteScore?: string;
  toeflScore?: string;
  insights?: string;
  gpa?: string;
  rankings?: {
    qsSubject?: number;
    usNewsSubject?: number;
  };
  sellingPoints?: string[];
}

export interface University {
  id: string;
  name: string;
  country: string;
  location: string;
  setting: 'Urban' | 'Suburban' | 'Rural' | 'City';
  logo: string;
  about: string;
  qsRanking?: number;
  otherRankings?: {
    usNewsGlobal?: number;
    national?: number;
  };
  acceptanceRate?: string;
  studentFacultyRatio?: string;
  internationalStudents?: string;
  type: 'Public' | 'Private';
  foundedYear?: number;
  applicationFee?: string;
  scholarships?: string;
  avgTuition: number;
  popularCourses: string[];
  programs: Program[];
}
export const universities: University[] = [
    {
        "id":  "boston-university",
        "name":  "Boston University",
        "country":  "USA",
        "location":  "Boston, MA",
        "setting":  "Urban",
        "logo":  "https://logo.clearbit.com/bu.edu",
        "about":  "A major private research university located in the heart of Boston, a vibrant hub of academia and innovation. BU offers a wide range of programs and is known for its strengths in medicine, law, and engineering. It has a large, diverse international student community.",
        "qsRanking":  93,
        "otherRankings":  {
                              "national":  43
                          },
        "acceptanceRate":  "14%",
        "studentFacultyRatio":  "10:1",
        "internationalStudents":  "24%",
        "type":  "Private",
        "foundedYear":  1839,
        "applicationFee":  "$95 USD",
        "scholarships":  "Boston University offers a limited number of merit-based scholarships for international graduate students. Funding is competitive and primarily administered by individual schools and departments.",
        "avgTuition":  66000,
        "popularCourses":  [
                               "Business",
                               "Communications",
                               "Engineering",
                               "Computer Science",
                               "Health Sciences",
                               "Cyber Security"
                           ],
        "programs":  [
                         {
                             "id":  "bu-cs-ms",
                             "name":  "MS in Computer Science",
                             "level":  "Masters",
                             "duration":  "1-2 years",
                             "tuition":  66670,
                             "school":  "Graduate School of Arts \u0026 Sciences",
                             "isSTEM":  true,
                             "about":  "A flexible program offering general computer science studies or specializations in areas like Cybersecurity and Data-Centric Computing. It is designed for students with a strong CS background.",
                             "requirements":  [
                                                  "B.S. in Computer Science or equivalent",
                                                  "Strong academic record",
                                                  "Letters of recommendation"
                                              ],
                             "applyLink":  "https://www.bu.edu/cs/academics/graduate/ms-in-cs/",
                             "ieltsScore":  "6.5+",
                             "toeflScore":  "90+ iBT",
                             "greScore":  "Not Required",
                             "gpa":  "3.3+",
                             "rankings":  {
                                              "usNewsSubject":  48
                                          },
                             "sellingPoints":  [
                                                   "Study in a Top Tech City: Immerse yourself in Boston\u0027s vibrant tech and biotech ecosystem with extensive networking opportunities.",
                                                   "Flexible Specializations: Choose a general track or specialize in high-demand fields like Cybersecurity or Data-Centric Computing.",
                                                   "Collaborate with Leading Faculty: Engage with renowned faculty in a program that balances strong theoretical foundations with practical application."
                                               ]
                         },
                         {
                             "id":  "bu-cs-ms-cyber",
                             "name":  "MS in Computer Science - Cyber Security",
                             "level":  "Masters",
                             "duration":  "1-2 years",
                             "tuition":  66670,
                             "school":  "Graduate School of Arts \u0026 Sciences",
                             "isSTEM":  true,
                             "about":  "A specialized track within the MS in CS program, focusing on the principles and practices of cybersecurity. Students delve into areas like cryptography, network security, and secure software development.",
                             "requirements":  [
                                                  "B.S. in Computer Science or equivalent",
                                                  "Strong academic record",
                                                  "Demonstrated interest in security"
                                              ],
                             "applyLink":  "https://www.bu.edu/cs/academics/graduate/ms-in-cs/",
                             "ieltsScore":  "6.5+",
                             "toeflScore":  "90+ iBT",
                             "greScore":  "Not Required",
                             "gpa":  "3.3+",
                             "rankings":  {
                                              "usNewsSubject":  48
                                          },
                             "sellingPoints":  [
                                                   "Deep Dive into Cybersecurity: A dedicated specialization to build expertise in one of tech\u0027s most critical fields.",
                                                   "Access to Security Research: Learn from faculty involved in cutting-edge cybersecurity research.",
                                                   "Boston Tech Hub: Benefit from Boston\u0027s strong ecosystem of security-focused companies for internships and careers."
                                               ]
                         }
                     ]
    },
    {
        "id":  "massachusetts-institute-of-technology",
        "name":  "Massachusetts Institute of Technology",
        "country":  "USA",
        "location":  "Cambridge, MA",
        "setting":  "Urban",
        "logo":  "https://logo.clearbit.com/mit.edu",
        "about":  "Established in 1861, the Massachusetts Institute of Technology (MIT) is a premier private research university renowned globally for its pioneering achievements in science, engineering, and technology. Located along the Charles River in Cambridge, Massachusetts, MIT fosters a culture of intense curiosity, rigorous hands-on learning, and bold innovation. International graduate students thrive in its highly collaborative, resource-rich research environment, which is designed to translate academic discoveries into real-world applications and global solutions.",
        "qsRanking":  1,
        "otherRankings":  {
                              "usNewsGlobal":  2,
                              "national":  2
                          },
        "acceptanceRate":  "11%",
        "studentFacultyRatio":  "3:1",
        "internationalStudents":  "41%",
        "type":  "Private",
        "foundedYear":  1861,
        "applicationFee":  "$90 USD",
        "scholarships":  "MIT offers merit-based fellowships, teaching assistantships, and research assistantships. Many PhD candidates receive full funding, and limited need- or merit-based support is available for Master\u0027s programs through individual departments.",
        "avgTuition":  66720,
        "popularCourses":  [
                               "Computer Science",
                               "Artificial Intelligence",
                               "Mechanical Engineering",
                               "Business Administration (MBA)",
                               "Data Science",
                               "Physics"
                           ],
        "programs":  [
                         {
                             "id":  "mit-sloan-mba",
                             "name":  "Master of Business Administration (MBA)",
                             "level":  "MBA",
                             "duration":  "2 years",
                             "tuition":  91892,
                             "school":  "MIT Sloan School of Management",
                             "isSTEM":  true,
                             "about":  "The MIT Sloan MBA program is a rigorous, two-year course of study that challenges students to find innovative solutions to real-world business and societal challenges. Known for its \u0027Action Learning\u0027 approach and strong focus on entrepreneurship and technological innovation, it is STEM-designated and prepares graduates to lead in a tech-driven world.",
                             "requirements":  [
                                                  "Four-year undergraduate degree or equivalent",
                                                  "GMAT or GRE score",
                                                  "Professional resume",
                                                  "Cover letter (300 words) and brief essay",
                                                  "One professional letter of recommendation (plus contacts for two others)",
                                                  "60-second video introduction",
                                                  "Organizational chart"
                                              ],
                             "applyLink":  "https://mitsloan.mit.edu/mba/admissions",
                             "ieltsScore":  "Waived (assessed via interview)",
                             "toeflScore":  "Waived (assessed via interview)",
                             "greScore":  "Required",
                             "gmatScore":  "Required",
                             "gpa":  "3.69 (Class Median)",
                             "insights":  "MIT Sloan values intellectual capability, leadership potential, and the ability to collaborate. The video essay is a critical component where admissions officers look for authenticity and communication skills. GMAT/GRE is required, so aim for a high score (median GMAT is typically around 720, and GMAT Focus median is 675).",
                             "rankings":  {
                                              "qsSubject":  3,
                                              "usNewsSubject":  5
                                          },
                             "sellingPoints":  [
                                                   "Action Learning Labs: Gain hands-on experience solving real business problems for global companies.",
                                                   "STEM Designation: The MBA is STEM-designated, allowing international students to apply for the 24-month OPT extension.",
                                                   "Entrepreneurship Ecosystem: Leverage the MIT Martin Trust Center for Entrepreneurship to launch your own venture."
                                               ]
                         },
                         {
                             "id":  "mit-sloan-mfin",
                             "name":  "Master of Finance (MFin)",
                             "level":  "Masters",
                             "duration":  "12-18 months",
                             "tuition":  93834,
                             "school":  "MIT Sloan School of Management",
                             "isSTEM":  true,
                             "about":  "The Master of Finance (MFin) program at MIT Sloan features a rigorous, hands-on curriculum that prepares students for careers in finance. Offering both 12-month and 18-month paths, the program is STEM-designated and focuses on the quantitative foundations of modern financial markets.",
                             "requirements":  [
                                                  "Four-year undergraduate degree or equivalent",
                                                  "Strong background in mathematics and programming (linear algebra, calculus, probability)",
                                                  "GMAT or GRE (Optional)",
                                                  "Professional resume",
                                                  "Essays and video questions",
                                                  "Three letters of recommendation"
                                              ],
                             "applyLink":  "https://mitsloan.mit.edu/mfin/admissions",
                             "ieltsScore":  "Waived (assessed via interview)",
                             "toeflScore":  "Waived (assessed via interview)",
                             "greScore":  "Optional",
                             "gmatScore":  "Optional",
                             "gpa":  "3.88 (Class Average)",
                             "insights":  "MIT Sloan MFin is extremely selective, looking for candidates with exceptional quantitative abilities. While GMAT/GRE is optional, submitting a high quantitative score can strengthen your application, especially if your academic background is not in a highly quantitative field.",
                             "rankings":  {
                                              "qsSubject":  3,
                                              "usNewsSubject":  5
                                          },
                             "sellingPoints":  [
                                                   "Curriculum Flexibility: Choose between a 12-month intensive path or an 18-month path that includes a summer internship.",
                                                   "Quantitative Focus: Build deep expertise in financial engineering, quantitative methods, and data-driven analysis.",
                                                   "Career Access: Recruit with top investment banks, hedge funds, asset management firms, and tech companies."
                                               ]
                         },
                         {
                             "id":  "mit-meche-ms",
                             "name":  "Master of Science in Mechanical Engineering (MSME)",
                             "level":  "Masters",
                             "duration":  "1.5-2 years",
                             "tuition":  66720,
                             "school":  "Department of Mechanical Engineering",
                             "isSTEM":  true,
                             "about":  "The MS program in Mechanical Engineering at MIT is a research-oriented degree that combines advanced coursework with a thesis. Students work closely with leading faculty on cutting-edge research in areas such as robotics, energy systems, manufacturing, and mechanics.",
                             "requirements":  [
                                                  "Bachelor\u0027s degree in engineering, science, or mathematics",
                                                  "GRE General Test is required",
                                                  "Statement of Objectives",
                                                  "Three letters of recommendation",
                                                  "English proficiency exam"
                                              ],
                             "applyLink":  "https://apply.mit.edu/apply/",
                             "ieltsScore":  "7.0+",
                             "toeflScore":  "100+ iBT",
                             "greScore":  "Required",
                             "gpa":  "3.8+",
                             "insights":  "MIT Mechanical Engineering is highly competitive and places a strong emphasis on research potential. Applicants should identify faculty members whose research aligns with their interests and reach out to them. High GRE scores (especially Quantitative in the 165+ range) and a strong GPA are recommended.",
                             "rankings":  {
                                              "qsSubject":  1,
                                              "usNewsSubject":  1
                                          },
                             "sellingPoints":  [
                                                   "World-Class Research Facilities: Access to state-of-the-art labs like the Pappalardo Micro-Robotics Lab and the d\u0027Arbeloff Laboratory.",
                                                   "Renowned Faculty: Work alongside pioneers in robotics, nanotechnology, biomechanics, and thermal-fluid sciences.",
                                                   "Industrial Partnerships: Benefit from MIT\u0027s close connections with leading aerospace, automotive, energy, and biomedical companies."
                                               ]
                         }
                     ]
    },
    {
        "id":  "stanford-university",
        "name":  "Stanford University",
        "country":  "USA",
        "location":  "Stanford, CA",
        "setting":  "Suburban",
        "logo":  "https://logo.clearbit.com/stanford.edu",
        "about":  "Located in the heart of Silicon Valley, Stanford University is a world-renowned private research institution. It is celebrated for its academic rigor, entrepreneurial culture, and close ties to the global technology sector. Its expansive, picturesque campus provides an inspiring backdrop for pioneering graduate research, making it a dream destination for students aiming to lead in science, engineering, and business.",
        "qsRanking":  6,
        "otherRankings":  {
                              "usNewsGlobal":  3,
                              "national":  3
                          },
        "acceptanceRate":  "4%",
        "studentFacultyRatio":  "5:1",
        "internationalStudents":  "25%",
        "type":  "Private",
        "foundedYear":  1885,
        "applicationFee":  "$125 USD",
        "scholarships":  "Stanford offers competitive fellowships, teaching assistantships, and research assistantships. Many PhD candidates receive full funding, and limited need- or merit-based support is available for Master\u0027s programs through individual departments.",
        "avgTuition":  65820,
        "popularCourses":  [
                               "Computer Science",
                               "Electrical Engineering",
                               "Business (MBA)",
                               "Data Science",
                               "Medicine"
                           ],
        "programs":  [
                         {
                             "id":  "stanford-cs-ms",
                             "name":  "MS in Computer Science",
                             "level":  "Masters",
                             "duration":  "1.5-2 years",
                             "tuition":  65820,
                             "school":  "School of Engineering",
                             "isSTEM":  true,
                             "about":  "A premier research-centric graduate program offering deep specialization tracks including Artificial Intelligence, Biocomputation, Software Theory, and Human-Computer Interaction.",
                             "requirements":  [
                                                  "Bachelor\u0027s degree in engineering or quantitative sciences",
                                                  "Strong mathematical and programming foundations",
                                                  "Three letters of recommendation",
                                                  "Statement of Purpose"
                                              ],
                             "applyLink":  "https://cs.stanford.edu/admissions/graduate-admissions",
                             "ieltsScore":  "7.0+",
                             "toeflScore":  "100+ iBT",
                             "greScore":  "Not Required",
                             "gpa":  "3.8+",
                             "rankings":  {
                                              "qsSubject":  2,
                                              "usNewsSubject":  1
                                          },
                             "sellingPoints":  [
                                                   "Silicon Valley Hub: Unmatched access to startups, venture capital, and tech giants for networking and internships.",
                                                   "World-Class Specialization: Take advanced, cutting-edge courses from global leaders in artificial intelligence and robotics.",
                                                   "Pioneering Research: Join state-of-the-art labs like the Stanford AI Lab (SAIL) or the Center for the Study of Language and Information."
                                               ]
                         }
                     ]
    },
    {
        "id":  "university-of-oxford",
        "name":  "University of Oxford",
        "country":  "UK",
        "location":  "Oxford, Oxfordshire",
        "setting":  "City",
        "logo":  "https://logo.clearbit.com/ox.ac.uk",
        "about":  "The oldest university in the English-speaking world, the University of Oxford is an iconic collegiate research institution in the United Kingdom. Oxford is renowned globally for its unparalleled academic heritage, world-leading research output, and unique tutorial-based learning environment. Its rich intellectual community, distributed across 39 self-governing colleges, offers international graduate students a truly historic and highly prestigious academic experience.",
        "qsRanking":  3,
        "otherRankings":  {
                              "usNewsGlobal":  5,
                              "national":  1
                          },
        "acceptanceRate":  "15%",
        "studentFacultyRatio":  "4:1",
        "internationalStudents":  "43%",
        "type":  "Public",
        "foundedYear":  1096,
        "applicationFee":  "£75 GBP",
        "scholarships":  "Oxford offers highly competitive funding schemes like the Clarendon Fund and Rhodes Scholarships. Most scholarships cover full tuition fees and provide a generous living stipend for the duration of the course.",
        "avgTuition":  56000,
        "popularCourses":  [
                               "Advanced Computer Science",
                               "Mathematics",
                               "Humanities",
                               "Public Policy",
                               "MBA"
                           ],
        "programs":  [
                         {
                             "id":  "oxford-cs-msc",
                             "name":  "MSc in Advanced Computer Science",
                             "level":  "Masters",
                             "duration":  "1 year",
                             "tuition":  56000,
                             "school":  "Department of Computer Science",
                             "isSTEM":  true,
                             "about":  "An intensive, elite postgraduate program designed to equip students with deep theoretical foundations and practical skills in advanced computer science, combining mathematical rigor with cutting-edge software theory.",
                             "requirements":  [
                                                  "First-class undergraduate degree with honors in Computer Science or Mathematics",
                                                  "Strong programming experience and discrete mathematics background",
                                                  "Three academic reference letters",
                                                  "Statement of purpose"
                                              ],
                             "applyLink":  "https://www.ox.ac.uk/admissions/graduate/courses/msc-advanced-computer-science",
                             "ieltsScore":  "7.5 (minimum 7.0 in each section)",
                             "toeflScore":  "110+ iBT",
                             "greScore":  "Not Required",
                             "gpa":  "3.85+",
                             "rankings":  {
                                              "qsSubject":  4,
                                              "usNewsSubject":  3
                                          },
                             "sellingPoints":  [
                                                   "Historic Collegiate System: Live and study inside Oxford\u0027s famous colleges, becoming part of a tight-knit intellectual community of scholars.",
                                                   "Renowned Oxford Tutorials: Engage directly with leading researchers in intimate, high-impact tutorial discussions.",
                                                   "Europe\u0027s AI Powerhouse: Study at the forefront of AI, machine learning, and quantum computing alongside award-winning computer science faculty."
                                               ]
                         }
                     ]
    }
];
