# GradNiche Windows Native Sync Compiler (PowerShell)
# Compiles raw JSON university profiles and blog posts into production TypeScript files.
# Bypasses Python/Node.js dependencies on Windows.

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$workspaceRoot = Split-Path -Parent $scriptPath

# -- PRODUCTION FLAG CHECK --
$useProduction = $args -contains "--production"
$uniOutputName = if ($useProduction) { "universities.ts" } else { "universities_compiled.ts" }
$blogOutputName = if ($useProduction) { "blogs.ts" } else { "blogs_compiled.ts" }

$uniOutputPath = Join-Path $workspaceRoot "data\$uniOutputName"
$blogOutputPath = Join-Path $workspaceRoot "data\$blogOutputName"

Write-Host "Target Output University File: $uniOutputPath"
Write-Host "Target Output Blogs File: $blogOutputPath"

# ==========================================
# 1. COMPILE UNIVERSITIES
# ==========================================
$uniPattern = Join-Path $workspaceRoot "data\universities\*.json"
$uniFiles = Get-ChildItem -Path $uniPattern -ErrorAction SilentlyContinue

Write-Host "Found $($uniFiles.Count) raw university JSON files."

$uniList = @()
foreach ($file in $uniFiles) {
    try {
        $raw = Get-Content -Path $file.FullName -Raw -Encoding utf8
        $json = ConvertFrom-Json -InputObject $raw
        
        # Mandatory field validation
        $required = @("id", "name", "country", "location", "setting", "logo", "about", "type", "avgTuition", "popularCourses", "programs")
        $missing = @()
        foreach ($r in $required) {
            if (-not $json.PSObject.Properties[$r]) { $missing += $r }
        }
        
        if ($missing.Count -eq 0) {
            $uniList += $json
        } else {
            Write-Host "[!] Skipping $($file.Name) due to missing properties: $missing" -ForegroundColor Yellow
        }
    } catch {
        Write-Host "[!] Error reading $($file.Name): $_" -ForegroundColor Red
    }
}

if ($uniList.Count -gt 0) {
    # Generate TypeScript content
    $ts = @"
// ============================================================================
// GradNiche University & Program Data Layer
// WARNING: This file is automatically compiled from raw JSON profiles.
// Do not edit this file directly. Instead, modify the JSON profiles under
// `/data/universities/` and run `scripts/sync.ps1` to compile.
// ============================================================================

export interface Program {
  id: string;
  name: string;
  level: 'Masters' | 'MBA';
  duration: string;
  tuition: number;
  about: string;
  school: string;
  isSTEM: boolean;
  requirements: string[];
  applyLink: string;
  ieltsScore?: string;
  greScore?: string;
  gmatScore?: string;
  duolingoScore?: string;
  pteScore?: string;
  toeflScore?: string;
  insights?: string;
  gpa?: string;
  rankings?: {
    qsSubject?: number;
    usNewsSubject?: number;
  };
  sellingPoints?: string[];
}

export interface University {
  id: string;
  name: string;
  country: string;
  location: string;
  setting: 'Urban' | 'Suburban' | 'Rural' | 'City';
  logo: string;
  about: string;
  qsRanking?: number;
  otherRankings?: {
    usNewsGlobal?: number;
    national?: number;
  };
  acceptanceRate?: string;
  studentFacultyRatio?: string;
  internationalStudents?: string;
  type: 'Public' | 'Private';
  foundedYear?: number;
  applicationFee?: string;
  scholarships?: string;
  avgTuition: number;
  popularCourses: string[];
  programs: Program[];
}

"@
    # Convert list back to formatted JSON
    $jsonString = ConvertTo-Json -InputObject $uniList -Depth 10
    $ts += "export const universities: University[] = $jsonString;`r`n"
    
    [System.IO.File]::WriteAllText($uniOutputPath, $ts, [System.Text.Encoding]::UTF8)
    Write-Host "[+] Successfully compiled $($uniList.Count) universities to $uniOutputPath" -ForegroundColor Green
}

# ==========================================
# 2. COMPILE BLOGS
# ==========================================
$existingBlogsTs = Join-Path $workspaceRoot "data\blogs.ts"
$blogList = @()

# Parse existing static blogs from data/blogs.ts via Regex
if (Test-Path $existingBlogsTs) {
    try {
        $content = Get-Content -Path $existingBlogsTs -Raw -Encoding utf8
        
        # Regex to match static blogs. We use double single quotes to escape single quotes in PowerShell.
        $pattern = '\{\s*id:\s*(\d+),\s*title:\s*"(.*?)",\s*excerpt:\s*"(.*?)",\s*author:\s*"(.*?)",\s*date:\s*"(.*?)",\s*readTime:\s*"(.*?)",\s*category:\s*"(.*?)",\s*image:\s*"(.*?)",\s*(?:visualType:\s*''(.*?)'',\s*)?content:\s*`(.*?)`\s*\}'
        $matches = [regex]::Matches($content, $pattern, [System.Text.RegularExpressions.RegexOptions]::Singleline)
        
        foreach ($m in $matches) {
            $blogList += [PSCustomObject]@{
                id = [int]$m.Groups[1].Value
                title = $m.Groups[2].Value.Replace('\"', '"')
                excerpt = $m.Groups[3].Value.Replace('\"', '"')
                author = $m.Groups[4].Value
                date = $m.Groups[5].Value
                readTime = $m.Groups[6].Value
                category = $m.Groups[7].Value
                image = $m.Groups[8].Value
                visualType = if ($m.Groups[9].Success) { $m.Groups[9].Value } else { $null }
                content = $m.Groups[10].Value.Trim()
            }
        }
        Write-Host "Parsed $($blogList.Count) existing static blogs from blogs.ts"
    } catch {
        Write-Host "[!] Warning parsing blogs.ts: $_. Starting fresh." -ForegroundColor Yellow
    }
}

# Load and validate new raw JSON blogs
$blogPattern = Join-Path $workspaceRoot "data\blogs\*.json"
$blogFiles = Get-ChildItem -Path $blogPattern -ErrorAction SilentlyContinue

Write-Host "Found $($blogFiles.Count) raw automated blog JSON files."

# Calculate next ID
$maxId = 0
foreach ($b in $blogList) { if ($b.id -gt $maxId) { $maxId = $b.id } }
$nextId = [Math]::Max(100, $maxId + 1)

$newBlogsCount = 0
foreach ($file in $blogFiles) {
    try {
        $raw = Get-Content -Path $file.FullName -Raw -Encoding utf8
        $json = ConvertFrom-Json -InputObject $raw
        
        $required = @("title", "excerpt", "author", "date", "readTime", "category", "image", "content")
        $missing = @()
        foreach ($r in $required) {
            if (-not $json.PSObject.Properties[$r]) { $missing += $r }
        }
        
        if ($missing.Count -eq 0) {
            # Add dynamic ID
            $json | Add-Member -MemberType NoteProperty -Name "id" -Value $nextId -Force
            $nextId++
            $blogList += $json
            $newBlogsCount++
        } else {
            Write-Host "[!] Skipping blog $($file.Name) due to missing properties: $missing" -ForegroundColor Yellow
        }
    } catch {
        Write-Host "[!] Error reading blog $($file.Name): $_" -ForegroundColor Red
    }
}

if ($blogList.Count -gt 0) {
    $tsBlogs = @"
// ============================================================================
// GradNiche Study Abroad Blogs Layer
// WARNING: This file is automatically compiled.
// Do not edit this file directly. Instead, add raw JSON files to `/data/blogs/`
// and run `scripts/sync.ps1` to compile.
// ============================================================================

export interface BlogPost {
    id: number;
    title: string;
    excerpt: string;
    author: string;
    date: string;
    readTime: string;
    category: string;
    image: string;
    content: string;
    visualType?: 'comparison' | 'cost-chart' | 'timeline' | 'scholarship-table' | 'university-list'; 
}

export const blogPosts: BlogPost[] = [
"@
    $tsBlogs += "`r`n"
    foreach ($blog in $blogList) {
        $tsBlogs += "    {`r`n"
        $tsBlogs += "        id: $($blog.id),`r`n"
        $titleEsc = $blog.title.Replace('"', '\"')
        $excerptEsc = $blog.excerpt.Replace('"', '\"')
        $tsBlogs += "        title: `"$titleEsc`",`r`n"
        $tsBlogs += "        excerpt: `"$excerptEsc`",`r`n"
        $tsBlogs += "        author: `"$($blog.author)`",`r`n"
        $tsBlogs += "        date: `"$($blog.date)`",`r`n"
        $tsBlogs += "        readTime: `"$($blog.readTime)`",`r`n"
        $tsBlogs += "        category: `"$($blog.category)`",`r`n"
        $tsBlogs += "        image: `"$($blog.image)`",`r`n"
        if ($blog.visualType) {
            $tsBlogs += "        visualType: '$($blog.visualType)',`r`n"
        }
        
        # Avoid complex double quote escaping inside method parameters by using single quotes
        $contentEsc = $blog.content.Replace('"', '\"').Replace('`', '\`').Replace('$', '\$')
        $tsBlogs += "        content: \`r`n$contentEsc\`r`n"
        $tsBlogs += "    },`r`n"
    }
    $tsBlogs += "];`r`n"
    
    [System.IO.File]::WriteAllText($blogOutputPath, $tsBlogs, [System.Text.Encoding]::UTF8)
    Write-Host "[+] Successfully compiled $($blogList.Count) blogs (New: $newBlogsCount) to $blogOutputPath" -ForegroundColor Green
}
