/**
 * GradNiche Data & Blog Synchronization compiler
 * Compiles raw JSON datasets (universities & blogs) into production TypeScript modules.
 * Run with node scripts/sync.js [--production]
 */

const fs = require('fs');
const path = require('path');

const useProduction = process.argv.includes('--production');
const uniOutputName = useProduction ? 'universities.ts' : 'universities_compiled.ts';
const blogOutputName = useProduction ? 'blogs.ts' : 'blogs_compiled.ts';

const dataDir = path.join(__dirname, '../data');
const uniOutputDir = path.join(dataDir, 'universities');
const blogOutputDir = path.join(dataDir, 'blogs');

console.log(`[*] Target Output:`);
console.log(`    - Universities: data/${uniOutputName}`);
console.log(`    - Blogs: data/${blogOutputName}`);

// ==========================================
// 1. COMPILE UNIVERSITIES
// ==========================================
if (fs.existsSync(uniOutputDir)) {
  const files = fs.readdirSync(uniOutputDir).filter(f => f.endsWith('.json'));
  console.log(`[*] Found ${files.length} raw university JSON files.`);
  
  const universities = [];
  for (const file of files) {
    try {
      const filepath = path.join(uniOutputDir, file);
      const raw = fs.readFileSync(filepath, 'utf8');
      const data = JSON.parse(raw);
      
      // Simple validation
      const required = ['id', 'name', 'country', 'location', 'setting', 'logo', 'about', 'type', 'avgTuition', 'popularCourses', 'programs'];
      const missing = required.filter(k => !data[k]);
      if (missing.length === 0) {
        universities.push(data);
      } else {
        console.warn(`[!] Skipping ${file} due to missing keys: ${missing.join(', ')}`);
      }
    } catch (e) {
      console.error(`[!] Error reading university ${file}:`, e.message);
    }
  }

  if (universities.length > 0) {
    const tsContent = `// ============================================================================
// GradNiche University & Program Data Layer
// WARNING: This file is automatically compiled from raw JSON profiles.
// Do not edit this file directly. Instead, modify the JSON profiles under
// \`/data/universities/\` and run \`node scripts/sync.js\` to compile.
// ============================================================================

export interface Program {
  id: string;
  name: string;
  level: 'Masters' | 'MBA';
  duration: string;
  tuition: number;
  about: string;
  school: string;
  isSTEM: boolean;
  requirements: string[];
  applyLink: string;
  ieltsScore?: string;
  greScore?: string;
  gmatScore?: string;
  duolingoScore?: string;
  pteScore?: string;
  toeflScore?: string;
  insights?: string;
  gpa?: string;
  rankings?: {
    qsSubject?: number;
    usNewsSubject?: number;
  };
  sellingPoints?: string[];
}

export interface University {
  id: string;
  name: string;
  country: string;
  location: string;
  setting: 'Urban' | 'Suburban' | 'Rural' | 'City';
  logo: string;
  about: string;
  qsRanking?: number;
  otherRankings?: {
    usNewsGlobal?: number;
    national?: number;
  };
  acceptanceRate?: string;
  studentFacultyRatio?: string;
  internationalStudents?: string;
  type: 'Public' | 'Private';
  foundedYear?: number;
  applicationFee?: string;
  scholarships?: string;
  avgTuition: number;
  popularCourses: string[];
  programs: Program[];
}

export const universities: University[] = ${JSON.stringify(universities, null, 2)};
`;
    fs.writeFileSync(path.join(dataDir, uniOutputName), tsContent, 'utf8');
    console.log(`[+] Successfully compiled ${universities.length} universities to data/${uniOutputName}`);
  }
}

// ==========================================
// 2. COMPILE BLOGS
// ==========================================
const blogsTsPath = path.join(dataDir, 'blogs.ts');
let blogList = [];

// Parse existing static blogs from data/blogs.ts
if (fs.existsSync(blogsTsPath)) {
  try {
    const content = fs.readFileSync(blogsTsPath, 'utf8');
    // Extract array content using regex
    const match = content.match(/export const blogPosts:\s*BlogPost\[\]\s*=\s*(\[[\s\S]*\]);/);
    if (match) {
      // Regex parsing for individual blog objects to preserve original HTML content
      const blogPattern = /\{\s*id:\s*(\d+),\s*title:\s*"([\s\S]*?)",\s*excerpt:\s*"([\s\S]*?)",\s*author:\s*"([\s\S]*?)",\s*date:\s*"([\s\S]*?)",\s*readTime:\s*"([\s\S]*?)",\s*category:\s*"([\s\S]*?)",\s*image:\s*"([\s\S]*?)",\s*(?:visualType:\s*'([\s\S]*?)',\s*)?content:\s*`([\s\S]*?)`\s*\}/g;
      
      let m;
      while ((m = blogPattern.exec(match[1])) !== null) {
        blogList.push({
          id: parseInt(m[1]),
          title: m[2].replace(/\\"/g, '"'),
          excerpt: m[3].replace(/\\"/g, '"'),
          author: m[4],
          date: m[5],
          readTime: m[6],
          category: m[7],
          image: m[8],
          visualType: m[9] || null,
          content: m[10].trim()
        });
      }
      console.log(`[*] Parsed ${blogList.length} existing static blogs from blogs.ts`);
    }
  } catch (e) {
    console.warn(`[!] Warning parsing blogs.ts: ${e.message}. Starting fresh.`);
  }
}

// Load and validate raw JSON blogs
if (fs.existsSync(blogOutputDir)) {
  const files = fs.readdirSync(blogOutputDir).filter(f => f.endsWith('.json'));
  console.log(`[*] Found ${files.length} raw automated blog JSON files.`);
  
  let maxId = 0;
  for (const b of blogList) {
    if (b.id > maxId) maxId = b.id;
  }
  let nextId = Math.max(100, maxId + 1);
  
  let newCount = 0;
  for (const file of files) {
    try {
      const filepath = path.join(blogOutputDir, file);
      const raw = fs.readFileSync(filepath, 'utf8');
      const data = JSON.parse(raw);
      
      const required = ['title', 'excerpt', 'author', 'date', 'readTime', 'category', 'image', 'content'];
      const missing = required.filter(k => !data[k]);
      if (missing.length === 0) {
        data.id = nextId++;
        blogList.push(data);
        newCount++;
      } else {
        console.warn(`[!] Skipping blog ${file} due to missing keys: ${missing.join(', ')}`);
      }
    } catch (e) {
      console.error(`[!] Error reading blog ${file}:`, e.message);
    }
  }

  if (blogList.length > 0) {
    let tsBlogsContent = `// ============================================================================
// GradNiche Study Abroad Blogs Layer
// WARNING: This file is automatically compiled.
// Do not edit this file directly. Instead, add raw JSON files to \`/data/blogs/\`
// and run \`node scripts/sync.js\` to compile.
// ============================================================================

export interface BlogPost {
    id: number;
    title: string;
    excerpt: string;
    author: string;
    date: string;
    readTime: string;
    category: string;
    image: string;
    content: string;
    visualType?: 'comparison' | 'cost-chart' | 'timeline' | 'scholarship-table' | 'university-list'; 
}

export const blogPosts: BlogPost[] = [
`;
    for (const blog of blogList) {
      tsBlogsContent += `    {\n`;
      tsBlogsContent += `        id: ${blog.id},\n`;
      tsBlogsContent += `        title: ${JSON.stringify(blog.title)},\n`;
      tsBlogsContent += `        excerpt: ${JSON.stringify(blog.excerpt)},\n`;
      tsBlogsContent += `        author: ${JSON.stringify(blog.author)},\n`;
      tsBlogsContent += `        date: ${JSON.stringify(blog.date)},\n`;
      tsBlogsContent += `        readTime: ${JSON.stringify(blog.readTime)},\n`;
      tsBlogsContent += `        category: ${JSON.stringify(blog.category)},\n`;
      tsBlogsContent += `        image: ${JSON.stringify(blog.image)},\n`;
      if (blog.visualType) {
        tsBlogsContent += `        visualType: '${blog.visualType}',\n`;
      }
      // Multiline content using backticks
      const escapedContent = blog.content.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
      tsBlogsContent += `        content: \`\n${escapedContent}\n        \`\n`;
      tsBlogsContent += `    },\n`;
    }
    tsBlogsContent += `];\n`;
    
    fs.writeFileSync(path.join(dataDir, blogOutputName), tsBlogsContent, 'utf8');
    console.log(`[+] Successfully compiled ${blogList.length} blogs (New: ${newCount}) to data/${blogOutputName}`);
  }
}
