#!/usr/bin/env python3
"""
GradNiche Data Synchronizer Bridge
Compiles all individual raw university JSON files in `data/universities/` 
into the unified `data/universities.ts` module used by the React frontend.
"""

import os
import sys
import json
import glob

# Ensure we have a non-destructive verification
def validate_university_profile(data: dict, file_path: str) -> bool:
    """Rigorous zero-dependency check for crucial schema fields to prevent frontend build failures."""
    required_keys = ["id", "name", "country", "location", "setting", "logo", "about", "type", "avgTuition", "popularCourses", "programs"]
    missing = [key for key in required_keys if key not in data]
    if missing:
        print(f"[!] Validation Error in {file_path}: Missing required keys {missing}", file=sys.stderr)
        return False
        
    # Check setting enum
    if data.get("setting") not in ["Urban", "Suburban", "Rural", "City"]:
        print(f"[!] Validation Error in {file_path}: 'setting' must be Urban, Suburban, Rural, or City.", file=sys.stderr)
        return False
        
    # Check type enum
    if data.get("type") not in ["Public", "Private"]:
        print(f"[!] Validation Error in {file_path}: 'type' must be Public or Private.", file=sys.stderr)
        return False
        
    # Verify programs array
    programs = data.get("programs", [])
    if not isinstance(programs, list):
        print(f"[!] Validation Error in {file_path}: 'programs' must be an array.", file=sys.stderr)
        return False
        
    prog_required = ["id", "name", "level", "duration", "tuition", "about", "school", "isSTEM", "requirements", "applyLink"]
    for i, prog in enumerate(programs):
        prog_missing = [k for k in prog_required if k not in prog]
        if prog_missing:
            print(f"[!] Validation Error in {file_path} (Program #{i}): Missing required keys {prog_missing}", file=sys.stderr)
            return False
        if prog.get("level") not in ["Masters", "MBA"]:
            print(f"[!] Validation Error in {file_path} (Program #{i}): 'level' must be Masters or MBA.", file=sys.stderr)
            return False
            
    return True

def main():
    workspace_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    json_pattern = os.path.join(workspace_root, "data", "universities", "*.json")
    
    # Non-destructive default: Compile to universities_compiled.ts in Phase 1
    # Use --production flag to overwrite the production universities.ts file
    use_production = "--production" in sys.argv
    output_filename = "universities.ts" if use_production else "universities_compiled.ts"
    output_ts_path = os.path.join(workspace_root, "data", output_filename)
    
    json_files = glob.glob(json_pattern)
    print(f"[*] Target Output File: {output_ts_path}")
    print(f"[*] Found {len(json_files)} raw university JSON profiles.")
    
    valid_profiles = []
    for jf in json_files:
        try:
            with open(jf, 'r', encoding='utf-8') as f:
                data = json.load(f)
            if validate_university_profile(data, jf):
                valid_profiles.append(data)
            else:
                print(f"[!] Skipping {jf} due to validation errors.")
        except Exception as e:
            print(f"[!] Error reading {jf}: {e}", file=sys.stderr)
            sys.exit(1)
            
    if not valid_profiles:
        print("[!] Warning: No valid raw university JSON files found to sync.")
        # We do not overwrite if no valid JSON profiles are found, to be safe.
        sys.exit(0)
        
    # Generate TypeScript code
    ts_content = """// ============================================================================
// GradNiche University & Program Data Layer
// WARNING: This file is automatically compiled from raw JSON profiles.
// Do not edit this file directly. Instead, modify the JSON profiles under
// `/data/universities/` and run `scripts/sync_data.py` to compile.
// ============================================================================

export interface Program {
  id: string;
  name: string;
  level: 'Masters' | 'MBA';
  duration: string;
  tuition: number;
  about: string;
  school: string;
  isSTEM: boolean;
  requirements: string[];
  applyLink: string;
  ieltsScore?: string;
  greScore?: string;
  gmatScore?: string;
  duolingoScore?: string;
  pteScore?: string;
  toeflScore?: string;
  insights?: string;
  gpa?: string;
  rankings?: {
    qsSubject?: number;
    usNewsSubject?: number;
  };
  sellingPoints?: string[];
}

export interface University {
  id: string;
  name: string;
  country: string;
  location: string;
  setting: 'Urban' | 'Suburban' | 'Rural' | 'City';
  logo: string;
  about: string;
  qsRanking?: number;
  otherRankings?: {
    usNewsGlobal?: number;
    national?: number;
  };
  acceptanceRate?: string;
  studentFacultyRatio?: string;
  internationalStudents?: string;
  type: 'Public' | 'Private';
  foundedYear?: number;
  applicationFee?: string;
  scholarships?: string;
  avgTuition: number;
  popularCourses: string[];
  programs: Program[];
}

"""
    # Write the array
    ts_content += "export const universities: University[] = "
    ts_content += json.dumps(valid_profiles, indent=2)
    ts_content += ";\n"
    
    # Save the file
    try:
        with open(output_ts_path, 'w', encoding='utf-8') as f:
            f.write(ts_content)
        print(f"[+] Successfully compiled {len(valid_profiles)} universities to {output_ts_path}")
    except Exception as e:
        print(f"[!] Failed to write universities.ts: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
